### ISSUE TITLE
List converters.

### ISSUE THREAD

**Issue by rgrinberg** [dbuenzli/astring#1]
Would be great to have `{to,of}_list`

**Comment by dbuenzli** [comment]
What are they supposed to do ?

**Comment by rgrinberg** [comment]
``` ocaml
val of_list : char list -> string
val to_list : string -> char list
```

**Comment by dbuenzli** [comment]
Why and when do you need this ?

**Comment by rgrinberg** [comment]
Usually you have an existing functions that take a list and you'd like to pass a string. I've found these useful for debugging occasionally. Also, core has these functions. Although I know that doesn't sound very convincing.

**Comment by dbuenzli** [comment]
> Although I know that doesn't sound very convincing.

Yes. 
1. It's better not to provide easy access to inefficient representations.
2. I never experienced the desire for such functions.
3. No compelling use case for this was shown to me.

So I'm closing this.

**Comment by raphael-proust** [comment]
@rgrinberg 
I agree with @dbuenzli : I can't see the use for converters. But I'm wondering if you would actually do with `fold_left: ('a -> char -> 'a) -> 'a -> string -> 'a` and other "list-like" functions on string.

I'm not sure if it has a place in `Astring`: including all the list-like functions might be a bit overkill. Specifically, neither the set-handling functions (`partition`, `filter`, &c.) nor the ordering (`merge`, `sort`, &c.) make sense for string handling.

Are there specific functions from the List module (beyond the ones that are already provdided: `hd`, `tl`, `append`, `concat`, `exists`, `for_all`, `nth`) that you would find actually useful? Do you have use cases for some additional list-like functions?
