### ISSUE TITLE
doesn't compile on ocaml.4.12.0+trunk due to injectivity changes

### ISSUE THREAD

**Issue by avsm** [dbuenzli/astring#18]
```
$ opam switch create 4.12.0+trunk
$ opam install astring
```
```
- File "src/astring.mli", lines 1049-1050, characters 12-42:
- 1049 | ............Map.S with type key := string
- 1050 |                    and type 'a t := 'a map
- Error: In this `with' constraint, the new definition of t
-        does not match its original definition in the constrained signature:
-        Type declarations do not match:
-          type 'a t = 'a map
-        is not included in
-          type +!'a t
-        Their variances do not agree.
-        File "map.mli", line 67, characters 4-15: Expected declaration
-        File "src/astring.mli", line 1050, characters 23-42:
-          Actual declaration
```

**Comment by dbuenzli** [comment]
There's a patch [floating here](https://github.com/yallop/astring/commit/97f7e109ff408fbca25635774ad89ce093f53926). We'll lose the short type names but I guess it's ok. @yallop can you confirm that's all what is needed ?

**Comment by yallop** [comment]
> @yallop can you confirm that's all what is needed ?

Yes, I believe it is.

**Comment by dbuenzli** [comment]
Thanks Anil for the report and Jeremy for the patch -- I'm not sneaking on you :-) I just saw by chance you forked `astring` on my gh timeline; that made me suspicious. 

New release [submitted to opam](https://github.com/ocaml/opam-repository/pull/16985).

Anil for full easy repro instructions you need to prepend :
 ```
opam repo add beta --set-default https://github.com/ocaml/ocaml-beta-repository.git
```
