### ISSUE TITLE
A simple function which can convert String to a List of String/Char

### ISSUE THREAD

**Issue by shubhamkumar13** [dbuenzli/astring#19]
Something of the type signature: `string -> string list` or `string -> char list`

Is that redundant? because sometimes I need to do something like `map` but instead of getting a string as an output, I'm more comfortable working with a string.

I'm not sure if that is worth it because it's a simple function like:
```ml
module String = Astring.String;;

let to_list str = String.fold_left (fun acc ch -> (String.of_char ch) :: acc) [] str;;
val to_list : string -> string list = <fun>
```

**Comment by dbuenzli** [comment]
> Is that redundant?

It's not redundant but it's a representation of strings that is very inefficient. One reason not to provide it is that it leads people into writing inefficient code.
