### ISSUE TITLE
Typos , typos (file astring.mli)

### ISSUE THREAD

**Issue by Fourchaux** [dbuenzli/astring#3]
Let's go :

L085  : /is_valid/is_digit/
L100-102 identical to L95-97 : 'copier-coller' strikes again !
L113  : /x0B/0x0B/
L114  : /x0C/0x0C/
L131  : /tranforms/transforms/
L150_932 : ... an non US-ASCII bytes. ???
L164  : /follows/follow/
L313  : /keep/keep_map/
L330  : /~first/~start/
L331  : /positions/position/
L353  : /neareast/nearest/
L379  : /seperator/separator/
L462  : /the the/the/
L573_1280  : /subtring/substring/
L610  : /compared /compared, /
L648  : sat ?
L666  : /statisfying/satisfying/ (la ligne de la Bête)
L683  : /statisfying/satisfying/ (la ligne 683)
L734  : /cut/cuts/
L793_801_809_817_1133_1141_1149_1157 : /respresentation/representation/ (THE WINNER is ...)
L805_1145  : /to_int/to_nativeint/
L813_1153  : /to_int/to_int32/
L821_1161  : /to_int/to_int64/
L829_1169  : /flaot/float/
L989  : /get_min_let/get_min_elt/
L1054 : /get_min/get_max/
L1107 : /in not/is not/
L1113 : /platorm/platform/
L1145 : /is an/is a/
L1227 : /a the top/at the top/
L1335 : /is is/is/

(Ouah, je suis fourbu après cette lecture de commentaires. Etonnant non ?)

And great code (as usual...)

**Comment by dbuenzli** [comment]
Thanks very much for the detailed report and review.

**Comment by Fourchaux** [comment]
Line 100 : /uppercase/lowercase/
Line 805 : /to_int/to_nativeint/
Line 813 : /to_int/to_int32/
Line 821 : /to_int/to_int64/

**Comment by dbuenzli** [comment]
Done. Thanks again.
