### ISSUE TITLE
Sedlex uses Char.code

### ISSUE THREAD

**Issue by objmagic** [dbuenzli/astring#6]
Sedlex uses `Char.code` when expanding ppx, but Astring uses `to_int`, I need to do

``` OCaml
module Char = struct
  include Char
  let code = to_int
end
```

Is there any better solution? Should I use this approach every time when code inserted by ppx is not compatible with third-party standard library overlay?

**Comment by dbuenzli** [comment]
Could you please show me an example where this happens ?

**Comment by objmagic** [comment]
now I think the question is more about Merlin

First, download this gist: https://gist.github.com/marklrh/5dd4374b7f5ba1bd3353

Then, open editor with Merlin plugin, I can see

![image](https://cloud.githubusercontent.com/assets/3656079/12016088/6546289c-acfb-11e5-9622-f658a446c6d5.png)

However, if I compile file with `ocamlbuild -use-ocamlfind -pkgs sedlex,astring,gen main.byte`, I can compile it with no problem.

But as I said, if I write this at the very beginning, there will be no Merlin error.

``` OCaml
module Char = struct
  include Char
  let code = to_int
end
```

**Comment by dbuenzli** [comment]
Did you add `astring` to your `.merlin` file ?

**Comment by objmagic** [comment]
Yes, I did, as you can see in https://gist.github.com/marklrh/5dd4374b7f5ba1bd3353#file-merlin

**Comment by dbuenzli** [comment]
Looks like a merlin bug no ?

**Comment by objmagic** [comment]
now it seems it looks like a Merlin bug. 

Sorry for raising a issue here, Daniel...
