### ISSUE TITLE
No documentation about what min and max mean in `String.drop`

### ISSUE THREAD

**Issue by timbertson** [dbuenzli/astring#8]
I haven't seen any "drop" implementation with both a min and a max before - looking at the code, it seems like it will perform no action unless the string is at least `min` length. Which kind of makes sense, but is not something I've ever seen - I assumed `min` was "the minimum number of characters to drop" and that `max` was maybe an endpoint (i.e. `str |> drop ~min:x ~max~y` would be shorthand for `str |> drop x |> take y`). So I actually tried doing `drop ~min:2 str` which I read as "drop a minimum of two characters (and if the string is shorter than that, just drop all of it)".

So yeah, some clarifying docs around these arguments might be useful. Also, it might be useful to make `~max` mandatory, since I can't think of any reasonable use of this API which omits it.

I'd even favour making it non-named (i.e. `drop n str`) or renaming it to len: `drop ~len:2 str`. But those would break the existing API, obviously.

**Comment by dbuenzli** [comment]
`drop` is defined in term of `span` where it seems to me the documentation is sufficently clear. 

> Also, it might be useful to make ~max mandatory, since I can't think of any reasonable use of this API which omits it.

Why ?

**Comment by timbertson** [comment]
> drop is defined in term of span where it seems to me the documentation is sufficently clear.

My apologies, I had scoured the page http://erratique.ch/software/astring/doc/Astring.html for references to "drop" and found nothing - but hadn't clicked through to http://erratique.ch/software/astring/doc/Astring.String.html which describes the relation to `span` fairly clearly.

> Why ? 

As I said above, I can't think of any case where omitting the `~max` argument would be useful, so it seems logical to make it mandatory. If you _can_ think of a use which omits `~max`, that would be a good argument for leaving it optional. I think making it mandatory would better convey correct use of the API, since it is far more obvious what "`drop` with one mandatory argument" means compared to "`drop` with a min and max argument, both of which are optional".

My initial problem was that from the API alone, I couldn't tell what `min` and `max` meant, and if `max` were mandatory that's much less likely to happen. It's just a suggestion, I personally don't need the clarification now but I still think it would make the API easier to understand. If you disagree, feel free to just close this issue.

**Comment by dbuenzli** [comment]
> If you can think of a use which omits ~max, that would be a good argument for leaving it optional.

``` ocaml
String.drop ~sat:Char.Ascii.is_white s
```

**Comment by timbertson** [comment]
Ahh, fair enough - hadn't thought of using it for a `trim`.

**Comment by dbuenzli** [comment]
But `trim`s only a prefix or a suffix (according to `rev`) not both at the same time. Use 

``` ocaml
String.trim ~drop:Char.Ascii.is_white s
```

for that.
